name=MLLServoConfigurator
version=1.0.0
author=Jueff
maintainer=Jueff <mobaledlib@gmx.at>
sentence=<h3>The library bundles servo related classes for MobaLedLib</h3>
paragraph=MLLServoConfigurator is an Arduino/Pico library for controlling and configuring up to three servo channels. ServoConfigurator implements a state machine for configuring up to three servo channels. It translates LED PWM signals into control commands, allows setting min/max limits, speed, and positions, and stores them persistently in flash memory. The class uses StatefulServoController instances for individual servo management and expects regular calls to process() for updates.
category=Signal Input/Output
url=https://github.com/Jueff/MLLServoConfigurator
architectures=rp2040
includes=ServoConfigurator.h,ServoController.h,StatefulServoController.h
depends=PicoFlashStorage