name=MLLServoConfigurator
version=0.1.0
author=Jueff
maintainer=Jueff (MobaLedLib@gmx.at)
sentence=<h3>The library bundles servo related classes for MobaLedLib</h3>
paragraph=0.1 release
category=Signal Input/Output
url=https://github.com/Jueff/MLLServoConfigurator
architectures=rp2040
includes=ServoConfigurator.h,ServoController.h,StatefulServoController.h
depends=PicoFlashStorage